# Generated by Django 4.1.7 on 2023-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('synopsis', models.TextField()),
                ('genre', models.TextField()),
                ('aired', models.TextField()),
                ('episodes', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('ranked', models.IntegerField()),
                ('score', models.FloatField()),
                ('img_url', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
