# Generated by Django 4.1.7 on 2023-04-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('episode_name', models.TextField(max_length=500)),
                ('synopsis', models.TextField()),
                ('aired', models.TextField()),
                ('img_url', models.TextField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_of', to='home.animedata')),
            ],
        ),
    ]
