# Generated by Django 4.1.7 on 2023-04-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_notification_is_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='anime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_of', to='home.animedata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('0', 'Completed'), ('1', 'Dropped'), ('2', 'Plan to Watch'), ('3', 'On Hold'), ('4', 'Watching')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
