# Generated by Django 4.1.7 on 2023-04-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notification_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode',
        ),
    ]
