# Generated by Django 4.1.7 on 2023-04-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_notification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationaudit_of', to='home.animedata')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_audits',
            field=models.ManyToManyField(blank=True, to='home.notificationaudit'),
        ),
    ]
