# Generated by Django 4.1.7 on 2023-05-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_animedata_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch'), ('on_hold', 'On Hold'), ('watching', 'Watching')], max_length=20),
        ),
    ]
