# Generated by Django 4.1.7 on 2023-05-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
